services:
  - type: web
    name: dataiatry-api
    env: docker
    region: oregon
    plan: free
    repo: "https://github.com/LimbergVillcaCoraite/dataIATry"
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
